//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMaker.Properties.Resources.zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录符号链接.
        /// </summary>
        public static string DirectorySymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("DirectorySymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接和目标位置在不同的磁盘上。.
        /// </summary>
        public static string DriveLetterNotEqualException {
            get {
                return ResourceManager.GetString("DriveLetterNotEqualException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你链接的拓展名与目标位置的拓展名不同，
        ///要为其添加 {0} 在末尾吗？.
        /// </summary>
        public static string ExtensionNotEqual {
            get {
                return ResourceManager.GetString("ExtensionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件符号链接.
        /// </summary>
        public static string FileSymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("FileSymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 硬链接.
        /// </summary>
        public static string HardLinkRadioButton {
            get {
                return ResourceManager.GetString("HardLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你拖拽的内容不合法。.
        /// </summary>
        public static string InvalidDraggedItem {
            get {
                return ResourceManager.GetString("InvalidDraggedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接所在目录的名称不合法。.
        /// </summary>
        public static string InvalidLinkDirectoryNameException {
            get {
                return ResourceManager.GetString("InvalidLinkDirectoryNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接名称不合法。.
        /// </summary>
        public static string InvalidLinkNameException {
            get {
                return ResourceManager.GetString("InvalidLinkNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联接.
        /// </summary>
        public static string JunctionLinkRadioButton {
            get {
                return ResourceManager.GetString("JunctionLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接创建成功。.
        /// </summary>
        public static string LinkCreatedTip {
            get {
                return ResourceManager.GetString("LinkCreatedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接的目录.
        /// </summary>
        public static string LinkDirectoryLabel {
            get {
                return ResourceManager.GetString("LinkDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个链接已经存在或已被占用了。.
        /// </summary>
        public static string LinkExistedException {
            get {
                return ResourceManager.GetString("LinkExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接模式.
        /// </summary>
        public static string LinkModeLabel {
            get {
                return ResourceManager.GetString("LinkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接名称.
        /// </summary>
        public static string LinkNameLabel {
            get {
                return ResourceManager.GetString("LinkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件.
        /// </summary>
        public static string SelectFileButton {
            get {
                return ResourceManager.GetString("SelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件夹.
        /// </summary>
        public static string SelectFolderButton {
            get {
                return ResourceManager.GetString("SelectFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择你想要创建的链接所在的目录.
        /// </summary>
        public static string SelectLinkDirectoryCaption {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个你想要被链接的文件.
        /// </summary>
        public static string SelectTargetFileCaption {
            get {
                return ResourceManager.GetString("SelectTargetFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个你想要被链接的文件夹.
        /// </summary>
        public static string SelectTargetFolderCaption {
            get {
                return ResourceManager.GetString("SelectTargetFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择目标.
        /// </summary>
        public static string SelectTargetPathButton {
            get {
                return ResourceManager.GetString("SelectTargetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标位置不存在。.
        /// </summary>
        public static string TargetNotFoundException {
            get {
                return ResourceManager.GetString("TargetNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标位置.
        /// </summary>
        public static string TargetPathLabel {
            get {
                return ResourceManager.GetString("TargetPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标位置应该为一个文件夹，而非文件。.
        /// </summary>
        public static string TargetRequireDirectoryException {
            get {
                return ResourceManager.GetString("TargetRequireDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标位置应该为一个文件，而非文件夹。.
        /// </summary>
        public static string TargetRequireFileException {
            get {
                return ResourceManager.GetString("TargetRequireFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
    }
}
