//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Link and the Target are in two Different Drive Letters! 的本地化字符串。
        /// </summary>
        public static string DifferentFromDriveLetterException {
            get {
                return ResourceManager.GetString("DifferentFromDriveLetterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target has already been a file but a directory! 的本地化字符串。
        /// </summary>
        public static string DirectorySymbolicLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("DirectorySymbolicLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dir SymLink 的本地化字符串。
        /// </summary>
        public static string DirectorySymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("DirectorySymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This dragged by you is invaild! 的本地化字符串。
        /// </summary>
        public static string DraggedThingIsNotVaild {
            get {
                return ResourceManager.GetString("DraggedThingIsNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your extension of Link&apos;s name is different from Target.
        ///Do you want to add {content} to Link&apos;s name at the end automatically or not. 的本地化字符串。
        /// </summary>
        public static string ExtensionIsNotSame {
            get {
                return ResourceManager.GetString("ExtensionIsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target has already been a directory but a file! 的本地化字符串。
        /// </summary>
        public static string FileSymbolicLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("FileSymbolicLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File SymLink 的本地化字符串。
        /// </summary>
        public static string FileSymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("FileSymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard Link Mode need the Target was file! 的本地化字符串。
        /// </summary>
        public static string HardLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("HardLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard Link 的本地化字符串。
        /// </summary>
        public static string HardLinkRadioButton {
            get {
                return ResourceManager.GetString("HardLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Junction Link Mode need both the Link and the Target are directory! 的本地化字符串。
        /// </summary>
        public static string JunctionLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("JunctionLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Junction Link 的本地化字符串。
        /// </summary>
        public static string JunctionLinkRadioButton {
            get {
                return ResourceManager.GetString("JunctionLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link&apos;s Directory: 的本地化字符串。
        /// </summary>
        public static string LinkDirectoryLabel {
            get {
                return ResourceManager.GetString("LinkDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Link&apos; directory is invalid!
        ///Please modify it. 的本地化字符串。
        /// </summary>
        public static string LinkDirectoryNameIsInvalidException {
            get {
                return ResourceManager.GetString("LinkDirectoryNameIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory which own the link you want to make isn&apos;t existed! 的本地化字符串。
        /// </summary>
        public static string LinkDirectroyIsNotExistedException {
            get {
                return ResourceManager.GetString("LinkDirectroyIsNotExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Link has been existed or occupied! 的本地化字符串。
        /// </summary>
        public static string LinkHasBeenExistedException {
            get {
                return ResourceManager.GetString("LinkHasBeenExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link&apos;s Mod: 的本地化字符串。
        /// </summary>
        public static string LinkModeLabel {
            get {
                return ResourceManager.GetString("LinkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Link&apos; name is invalid!
        ///Please modify it. 的本地化字符串。
        /// </summary>
        public static string LinkNameIsInvalidException {
            get {
                return ResourceManager.GetString("LinkNameIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link&apos;s Name: 的本地化字符串。
        /// </summary>
        public static string LinkNameLabel {
            get {
                return ResourceManager.GetString("LinkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need select the Link Mode! 的本地化字符串。
        /// </summary>
        public static string NotSelectLinkModeException {
            get {
                return ResourceManager.GetString("NotSelectLinkModeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        public static string SelectLinkDirectoryButton {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a directory where you want to create the link 的本地化字符串。
        /// </summary>
        public static string SelectLinkDirectoryCaption {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        public static string SelectLinkFileButton {
            get {
                return ResourceManager.GetString("SelectLinkFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        public static string SelectTargetFileButton {
            get {
                return ResourceManager.GetString("SelectTargetFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a file you want to be linked 的本地化字符串。
        /// </summary>
        public static string SelectTargetFileCaption {
            get {
                return ResourceManager.GetString("SelectTargetFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        public static string SelectTargetFolderButton {
            get {
                return ResourceManager.GetString("SelectTargetFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a folder you want to be linked 的本地化字符串。
        /// </summary>
        public static string SelectTargetFolderCaption {
            get {
                return ResourceManager.GetString("SelectTargetFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Target 的本地化字符串。
        /// </summary>
        public static string SelectTargetPathButton {
            get {
                return ResourceManager.GetString("SelectTargetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Target hasn&apos;t existed yet. 的本地化字符串。
        /// </summary>
        public static string TargetHasNotExistedYet {
            get {
                return ResourceManager.GetString("TargetHasNotExistedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Target is neither file nor directory! 的本地化字符串。
        /// </summary>
        public static string TargetNeitherFileNorDirectoryException {
            get {
                return ResourceManager.GetString("TargetNeitherFileNorDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target&apos;s Path: 的本地化字符串。
        /// </summary>
        public static string TargetPathLabel {
            get {
                return ResourceManager.GetString("TargetPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string WhetherContinue {
            get {
                return ResourceManager.GetString("WhetherContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to craete the Target directory automatically? 的本地化字符串。
        /// </summary>
        public static string WhetherMkDirTarget {
            get {
                return ResourceManager.GetString("WhetherMkDirTarget", resourceCulture);
            }
        }
    }
}
