//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMaker.Properties.zh", typeof(zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接和目标位置的磁盘驱动器符号不同！ 的本地化字符串。
        /// </summary>
        public static string DifferentFromDriveLetterException {
            get {
                return ResourceManager.GetString("DifferentFromDriveLetterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你拖拽的内容不合法！ 的本地化字符串。
        /// </summary>
        public static string DraggedThingIsNotVaild {
            get {
                return ResourceManager.GetString("DraggedThingIsNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你链接的拓展名与目标位置的拓展名不同，
        ///你想要自动为其添加 的本地化字符串。
        /// </summary>
        public static string ExtensionIsNotSame_1 {
            get {
                return ResourceManager.GetString("ExtensionIsNotSame_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在末尾吗？ 的本地化字符串。
        /// </summary>
        public static string ExtensionIsNotSame_2 {
            get {
                return ResourceManager.GetString("ExtensionIsNotSame_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬链接模式需要链接和目标位置都是文件！ 的本地化字符串。
        /// </summary>
        public static string HardLinkIsInapplicableExcption {
            get {
                return ResourceManager.GetString("HardLinkIsInapplicableExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬链接 的本地化字符串。
        /// </summary>
        public static string HardLinkRadioButton {
            get {
                return ResourceManager.GetString("HardLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联接模式需要链接和目标位置都是文件夹！ 的本地化字符串。
        /// </summary>
        public static string JunctionLinkIsInapplicableExcption {
            get {
                return ResourceManager.GetString("JunctionLinkIsInapplicableExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联接 的本地化字符串。
        /// </summary>
        public static string JunctionLinkRadioButton {
            get {
                return ResourceManager.GetString("JunctionLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要创建的链接的目录： 的本地化字符串。
        /// </summary>
        public static string LinkDirectoryLabel {
            get {
                return ResourceManager.GetString("LinkDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你想要创建的链接所在的目录不存在！ 的本地化字符串。
        /// </summary>
        public static string LinkDirectroyIsNotExistedException {
            get {
                return ResourceManager.GetString("LinkDirectroyIsNotExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个链接已经存在了！ 的本地化字符串。
        /// </summary>
        public static string LinkHasBeenExistedException {
            get {
                return ResourceManager.GetString("LinkHasBeenExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接模式： 的本地化字符串。
        /// </summary>
        public static string LinkModeLabel {
            get {
                return ResourceManager.GetString("LinkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接名称不合法！
        ///请修改后再试。 的本地化字符串。
        /// </summary>
        public static string LinkNameIsInvalidException {
            get {
                return ResourceManager.GetString("LinkNameIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接名称： 的本地化字符串。
        /// </summary>
        public static string LinkNameLabel {
            get {
                return ResourceManager.GetString("LinkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你需要先选择链接模式！ 的本地化字符串。
        /// </summary>
        public static string NotSelectLinkModeException {
            get {
                return ResourceManager.GetString("NotSelectLinkModeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件夹 的本地化字符串。
        /// </summary>
        public static string SelectLinkDirectoryButton {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择你想要创建的链接所在的目录 的本地化字符串。
        /// </summary>
        public static string SelectLinkDirectoryCaption {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标位置 的本地化字符串。
        /// </summary>
        public static string SelectTargetPathButton {
            get {
                return ResourceManager.GetString("SelectTargetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个你想要被链接的目标位置 的本地化字符串。
        /// </summary>
        public static string SelectTargetPathCaption {
            get {
                return ResourceManager.GetString("SelectTargetPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 符号链接 的本地化字符串。
        /// </summary>
        public static string SymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("SymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标位置既不是文件，也不是文件夹 的本地化字符串。
        /// </summary>
        public static string TargetNeitherFileNorDirectoryExcption {
            get {
                return ResourceManager.GetString("TargetNeitherFileNorDirectoryExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标位置： 的本地化字符串。
        /// </summary>
        public static string TargetPathLabel {
            get {
                return ResourceManager.GetString("TargetPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
    }
}
