//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link and the target are on two different drives..
        /// </summary>
        public static string DifferentFromDriveLetterException {
            get {
                return ResourceManager.GetString("DifferentFromDriveLetterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is a file but not a directory..
        /// </summary>
        public static string DirectorySymbolicLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("DirectorySymbolicLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir SymLink.
        /// </summary>
        public static string DirectorySymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("DirectorySymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you dragged is invaild..
        /// </summary>
        public static string DraggedThingIsNotVaild {
            get {
                return ResourceManager.GetString("DraggedThingIsNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link&apos;s extension is different from the target.
        ///Do you want to add {0} to Link&apos;s name at the end?.
        /// </summary>
        public static string ExtensionIsNotSame {
            get {
                return ResourceManager.GetString("ExtensionIsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is a directory but not a file..
        /// </summary>
        public static string FileSymbolicLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("FileSymbolicLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File SymLink.
        /// </summary>
        public static string FileSymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("FileSymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Link Mode requires the target to be a file..
        /// </summary>
        public static string HardLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("HardLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Link.
        /// </summary>
        public static string HardLinkRadioButton {
            get {
                return ResourceManager.GetString("HardLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction Link Mode requires the target to be a directory..
        /// </summary>
        public static string JunctionLinkIsInapplicableException {
            get {
                return ResourceManager.GetString("JunctionLinkIsInapplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction Link.
        /// </summary>
        public static string JunctionLinkRadioButton {
            get {
                return ResourceManager.GetString("JunctionLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link&apos;s Directory.
        /// </summary>
        public static string LinkDirectoryLabel {
            get {
                return ResourceManager.GetString("LinkDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Link&apos; directory is invalid!
        ///Please modify it..
        /// </summary>
        public static string LinkDirectoryNameIsInvalidException {
            get {
                return ResourceManager.GetString("LinkDirectoryNameIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory which own the link you want to make isn&apos;t existed!.
        /// </summary>
        public static string LinkDirectroyIsNotExistedException {
            get {
                return ResourceManager.GetString("LinkDirectroyIsNotExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Link has been existed or occupied!.
        /// </summary>
        public static string LinkHasBeenExistedException {
            get {
                return ResourceManager.GetString("LinkHasBeenExistedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link&apos;s Mode.
        /// </summary>
        public static string LinkModeLabel {
            get {
                return ResourceManager.GetString("LinkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Link&apos; name is invalid!
        ///Please modify it..
        /// </summary>
        public static string LinkNameIsInvalidException {
            get {
                return ResourceManager.GetString("LinkNameIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link&apos;s Name.
        /// </summary>
        public static string LinkNameLabel {
            get {
                return ResourceManager.GetString("LinkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need select the Link Mode!.
        /// </summary>
        public static string NotSelectLinkModeException {
            get {
                return ResourceManager.GetString("NotSelectLinkModeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectLinkDirectoryButton {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory where you want to create the link.
        /// </summary>
        public static string SelectLinkDirectoryCaption {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectLinkFileButton {
            get {
                return ResourceManager.GetString("SelectLinkFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectTargetFileButton {
            get {
                return ResourceManager.GetString("SelectTargetFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file you want to be linked.
        /// </summary>
        public static string SelectTargetFileCaption {
            get {
                return ResourceManager.GetString("SelectTargetFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectTargetFolderButton {
            get {
                return ResourceManager.GetString("SelectTargetFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder you want to be linked.
        /// </summary>
        public static string SelectTargetFolderCaption {
            get {
                return ResourceManager.GetString("SelectTargetFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target.
        /// </summary>
        public static string SelectTargetPathButton {
            get {
                return ResourceManager.GetString("SelectTargetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target hasn&apos;t existed yet..
        /// </summary>
        public static string TargetHasNotExistedYet {
            get {
                return ResourceManager.GetString("TargetHasNotExistedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target is neither file nor directory!.
        /// </summary>
        public static string TargetNeitherFileNorDirectoryException {
            get {
                return ResourceManager.GetString("TargetNeitherFileNorDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target&apos;s Path.
        /// </summary>
        public static string TargetPathLabel {
            get {
                return ResourceManager.GetString("TargetPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string WhetherContinue {
            get {
                return ResourceManager.GetString("WhetherContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to craete the Target directory automatically?.
        /// </summary>
        public static string WhetherMkDirTarget {
            get {
                return ResourceManager.GetString("WhetherMkDirTarget", resourceCulture);
            }
        }
    }
}
