//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard link 的本地化字符串。
        /// </summary>
        public static string HardLinkRadioButton {
            get {
                return ResourceManager.GetString("HardLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Junction link 的本地化字符串。
        /// </summary>
        public static string JunctionLinkRadioButton {
            get {
                return ResourceManager.GetString("JunctionLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Link&apos;s directory: 的本地化字符串。
        /// </summary>
        public static string LinkDirectoryLabel {
            get {
                return ResourceManager.GetString("LinkDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Link&apos;s mod: 的本地化字符串。
        /// </summary>
        public static string LinkModeLabel {
            get {
                return ResourceManager.GetString("LinkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Link&apos;s name: 的本地化字符串。
        /// </summary>
        public static string LinkNameLabel {
            get {
                return ResourceManager.GetString("LinkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        public static string SelectLinkDirectoryButton {
            get {
                return ResourceManager.GetString("SelectLinkDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Target 的本地化字符串。
        /// </summary>
        public static string SelectTargetPathButton {
            get {
                return ResourceManager.GetString("SelectTargetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbolic link 的本地化字符串。
        /// </summary>
        public static string SymbolicLinkRadioButton {
            get {
                return ResourceManager.GetString("SymbolicLinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Target&apos;s path: 的本地化字符串。
        /// </summary>
        public static string TargetPathLabel {
            get {
                return ResourceManager.GetString("TargetPathLabel", resourceCulture);
            }
        }
    }
}
